import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import dynamicRouter from './routes/dynamic.js';
import authRouter from './routes/auth.js';
import prisma from './lib/prisma.js';
import { syncSchema } from './lib/schema-sync.js';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

// Routes
app.use('/api/auth', authRouter);
app.use('/api/data', dynamicRouter);

// Endpoint to update app configuration
app.post('/api/config', async (req, res) => {
  try {
    const config = req.body;
    const ownerId = 'default-user-id'; // Mock

    // Save arbitrary config to DB
    const savedConfig = await prisma.appConfig.upsert({
      where: { id: 'current-config' }, // Simplified for MVP
      create: {
        id: 'current-config',
        name: config.appName || 'Dynamic App',
        config: config as any,
        ownerId
      },
      update: {
        name: config.appName || 'Dynamic App',
        config: config as any
      },
    });

    // Sync database schema if entities are defined
    if (config.entities && Array.isArray(config.entities)) {
      await syncSchema(config.entities);
    }

    res.json({ message: 'Configuration deployed successfully', config: savedConfig });
  } catch (error: any) {
    console.error('Configuration deployment error:', error);
    res.status(400).json({ error: error.message });
  }
});

app.delete('/api/config', async (req, res) => {
  try {
    await prisma.appConfig.deleteMany({}); // Clear all for now
    res.json({ message: 'Configuration cleared successfully' });
  } catch (error: any) {
    console.error('Configuration clear error:', error);
    res.status(500).json({ error: error.message });
  }
});

app.get('/api/config', async (req, res) => {
  const config = await prisma.appConfig.findFirst();
  res.json(config?.config || null);
});

// Mock GitHub Export Integration
app.post('/api/export/github', async (req, res) => {
  const config = await prisma.appConfig.findFirst();
  if (!config) return res.status(404).json({ error: 'No configuration found to export' });

  // Simulate generating project files
  const projectStructure = {
    repository: `generated-${config.name.toLowerCase().replace(/\s+/g, '-')}`,
    files: [
      { path: 'package.json', content: '{ "name": "generated-app", "version": "1.0.0" }' },
      { path: 'schema.prisma', content: '// Generated Prisma Schema...' },
      { path: 'config.json', content: JSON.stringify(config.config) },
      { path: 'README.md', content: `# ${config.name}\nGenerated by Superagent Runtime` }
    ]
  };

  // In a real scenario, we would use Octokit to push to a repo.
  // For now, we return the structure to show it's "integrated".
  res.json({ message: 'Project structure generated and pushed to mock repository', structure: projectStructure });
});

// Mock Transactional Email System
app.post('/api/notify/email', async (req, res) => {
  const { to, subject, body } = req.body;
  console.log(`[MOCK EMAIL] Sending to: ${to} | Subject: ${subject}`);
  console.log(`[MOCK EMAIL] Body: ${body}`);
  
  res.json({ message: 'Transactional email sent successfully (Mock)' });
});

app.listen(PORT, async () => {
  console.log(`Aether Server running on http://localhost:${PORT}`);
  
  // Ensure default user exists for the mock ownerId
  try {
    await prisma.user.upsert({
      where: { id: 'default-user-id' },
      update: {},
      create: {
        id: 'default-user-id',
        email: 'admin@aether.ai',
        password: 'admin-password-mock'
      }
    });
  } catch (e) {
    console.error('Failed to create default user:', e);
  }
});

// Panic handlers
process.on('unhandledRejection', (reason, promise) => {
  console.error('Unhandled Rejection at:', promise, 'reason:', reason);
});

process.on('uncaughtException', (err) => {
  console.error('Uncaught Exception:', err);
});

// Simple keep-alive to prevent premature exit in some environments
setInterval(() => {}, 1000 * 60 * 60); 
